// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Generate Deep Agents Code config.toml from NemoClaw build-arg env vars.
//
// SECURITY: this file writes only non-secret provider/model metadata. Real
// provider credentials stay outside ~/.deepagents files.

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

type Settings = {
  model: string;
  baseUrl: string;
  providerKey: string;
  upstreamProvider: string;
  inferenceApi: string;
};

function readSettings(env: NodeJS.ProcessEnv): Settings {
  return {
    model: readRequiredEnv(env, "NEMOCLAW_MODEL"),
    baseUrl: env.NEMOCLAW_INFERENCE_BASE_URL || "https://inference.local/v1",
    providerKey: env.NEMOCLAW_PROVIDER_KEY || "inference",
    upstreamProvider: env.NEMOCLAW_UPSTREAM_PROVIDER || env.NEMOCLAW_PROVIDER_KEY || "inference",
    inferenceApi: env.NEMOCLAW_INFERENCE_API || "openai-completions",
  };
}

function readRequiredEnv(env: NodeJS.ProcessEnv, name: string): string {
  const value = env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function modelNameForOpenAiProvider(model: string): string {
  const trimmed = model.trim();
  const providerSeparator = trimmed.indexOf(":");
  if (providerSeparator > 0) {
    return trimmed.slice(providerSeparator + 1);
  }
  return trimmed;
}

function buildConfig(settings: Settings): string {
  const model = modelNameForOpenAiProvider(settings.model);
  const defaultModel = `openai:${model}`;
  return [
    "# Generated by NemoClaw. This file contains no provider secrets.",
    `# NemoClaw provider route: ${settings.providerKey}; upstream provider: ${settings.upstreamProvider}; API: ${settings.inferenceApi}.`,
    "",
    "[models]",
    `default = ${tomlString(defaultModel)}`,
    "",
    "[models.providers.openai]",
    `models = ${tomlArray([model])}`,
    'api_key_env = "DEEPAGENTS_CODE_OPENAI_API_KEY"',
    `base_url = ${tomlString(settings.baseUrl)}`,
    "enabled = true",
    "",
    "[models.providers.openai.params]",
    "use_responses_api = false",
    "",
    "[update]",
    "auto_update = false",
    "",
  ].join("\n");
}

function main(): void {
  const settings = readSettings(process.env);
  const configDir = join(homedir(), ".deepagents");
  mkdirSync(join(configDir, ".state"), { recursive: true, mode: 0o770 });
  mkdirSync(join(configDir, "skills"), { recursive: true, mode: 0o770 });

  const configPath = join(configDir, "config.toml");
  writeFileSync(configPath, buildConfig(settings));
  chmodSync(configPath, 0o600);

  console.log(
    `[config] Wrote ${configPath} (model=openai:${modelNameForOpenAiProvider(settings.model)}, base_url=${settings.baseUrl})`,
  );
}

main();
